CREATE TABLE IF NOT EXISTS Przekaski (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nazwa VARCHAR(30) NOT NULL,
    cena INT NOT NULL
    )

CREATE TABLE IF NOT EXISTS Napoje (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nazwa VARCHAR(30) NOT NULL,
    cena INT NOT NULL
    )

CREATE TABLE IF NOT EXISTS Sala (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    stan INT NOT NULL
    )

CREATE TABLE IF NOT EXISTS Bilet (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    typ VARCHAR(30) NOT NULL,
    cena INT
    )
CREATE TABLE IF NOT EXISTS Seans ( 
id INT NOT NULL AUTO_INCREMENT,
 nazwa_filmu VARCHAR(30) NOT NULL,
 godzina DATETIME, id_sala INT,
 id_bilet INT, PRIMARY KEY(id),
 FOREIGN KEY(id_sala) REFERENCES sala(id),
 FOREIGN KEY(id_bilet) REFERENCES bilet(id)
)
